### ISSUE TITLE
I cant import bmps

### ISSUE THREAD

**Issue by korbosoft** [wyskoj/HWFEditor#1]
i am losing my mind

**Comment by korbosoft** [comment]
all it says is nO FiLe lOaDeD1!1!!!!!!

**Comment by wyskoj** [comment]
When is it hanging? When you're loading an HWF file?

**Comment by korbosoft** [comment]
yes nothing happens and when i hover over the program after that it gives me the busy cursor.

**Comment by wyskoj** [comment]
Try launching the program from the command line `java -jar HWFEditor-1.1.jar` and see if any errors appear in the console.

**Comment by korbosoft** [comment]
as soon as i click open A BUNCH of errors appeared.
`Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Unknown Source)
        at org.wysko.hwfeditor.HWFEditor.parseHWF(HWFEditor.java:151)
        at org.wysko.hwfeditor.HWFEditor.loadHWF(HWFEditor.java:201)
        at org.wysko.hwfeditor.HWFEditor.openMenuItemActionPerformed(HWFEditor.java:314)
        at org.wysko.hwfeditor.HWFEditor.lambda$initComponents$1(HWFEditor.java:542)
        at org.wysko.hwfeditor.HWFEditor$$Lambda$38/16153462.actionPerformed(Unknown Source)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
`

**Comment by korbosoft** [comment]
i saw OutOfMemoryError, and i have 113 gb free on the drive. again, im no java expert, let alone even tried it.

**Comment by korbosoft** [comment]
i have windows 10, by the way. probably its fault, knowing windows 10.

**Comment by wyskoj** [comment]
This is a RAM issue, not storage. Let me know how much total RAM you have (Task Manager | Performance | Memory). Try closing any other applications and try opening the file again. The parsing algorithm isn't exactly memory efficient so this is probably the issue.

**Comment by korbosoft** [comment]
5.4/7.8 GB 68%

**Comment by korbosoft** [comment]
still doesn't work
gives same error

**Comment by wyskoj** [comment]
Okay, this is something I will need to fix.

**Comment by wyskoj** [comment]
@KorbinCode Try unzipping this then launching the jar with `java -jar HWFEditor-1.2-SNAPSHOT.jar` and let me know how it goes.

[HWFEditor-1.2-SNAPSHOT.zip](https://github.com/wyskoj/HWFEditor/files/4929110/HWFEditor-1.2-SNAPSHOT.zip)

**Comment by korbosoft** [comment]
There was an error parsing the HWF file.

org.wysko.hwfeditor.HWFEditor$IllformattedHWFFile: Illegal EOF at position 18266914.
when i press ok
the console barfs out this
org.wysko.hwfeditor.HWFEditor$IllformattedHWFFile: Illegal EOF at position 18266914.
        at org.wysko.hwfeditor.HWFEditor.betterParseHWF(HWFEditor.java:156)
        at org.wysko.hwfeditor.HWFEditor.loadHWF(HWFEditor.java:249)
        at org.wysko.hwfeditor.HWFEditor.openMenuItemActionPerformed(HWFEditor.java:365)
        at org.wysko.hwfeditor.HWFEditor.lambda$initComponents$2(HWFEditor.java:594)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by wyskoj** [comment]
Try a clean HWF file from source. Still get the same error?

**Comment by korbosoft** [comment]
what do you mean?

**Comment by korbosoft** [comment]
nevermind i dragged the hwf file to the editors location and now it somehow works

**Comment by korbosoft** [comment]
i cant import bmps

**Comment by korbosoft** [comment]
original title: Hangs when i try to load file

**Comment by wyskoj** [comment]
You gotta give me some context, an error, crash? What's preventing you from importing BMPs?

**Comment by wyskoj** [comment]
Upload the BMP that is giving you trouble too.

**Comment by wyskoj** [comment]
Should be fixed by [v1.2](https://github.com/wyskoj/HWFEditor/releases/tag/v1.2)
